zuul:
  prefix: /api
  ignored-services: '*'
  routes:
    manageuser:
      path: /ManageUser/**
      serviceId: MANAGE-USER
ribbon:
  eureka:
    enabled: false
MANAGE-USER:
  ribbon:
    listOfServers: 127.0.0.1:8906
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 12000
spring:
  zipkin:
    base-url: http://localhost:8903/
  jmx:
    default-domain: ${spring.application.name}